### ISSUE TITLE
Add an option to set colors for roles

### ISSUE THREAD

**Issue by BoOmka** [michaelwestbrook/Provinatus#89]
In Provision's TeamFormation there was an option to use role icons instead of class. They looked ugly and unreadable.
I'd like to choose to show whether player's hp as icon color or player's role. Helps a lot when you hear "Tank's down" in your discord and there is a lot of dead people laying around and you need to find the tank.
Also there was a great feature to set custom color to certain character.

**Comment by BoOmka** [comment]
relates to #38

**Comment by michaelwestbrook** [comment]
Re-added the ability to display role icons. They are still ugly but you can change their size and opacity in the settings menu. Now onto setting color for icons.
